name: "إعادة تسمية الصور سحابياً"
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  rename:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - run: python automation/cloud_rename.py
      - run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add assets/images/ || echo "No images"
          git commit -m "مَيْكَنَةُ الأَسْمَاءِ [Node 24]" || echo "No changes"
          git push
